NAME = philo
INCLUDE = ./include/philo.h
CC = gcc
CFLAGS = -Werror -Wlan -Wextra -g
SRC = philo.c
OBJ = $(addprefix $(OBJ_DIR)/, $(SRC:%.c=%.o))
OBJ_DIR = obj
SRC_DIR = src
RM = rm -rf
NORMI = norminette
NORM_FOLDER = ./src ./include ./obj

all:

$(NAME):

$(OBJ_DIR)/%.o: %.c

obj_dir:
	mkdir -p $(OBJ-_DIR)

clean:

fclean:

re:

norm:

.PHONY: all clean fclean re norm obj_dir
